# Continuous integration configuration for Travis
# NB use https://config.travis-ci.com/explore to validate changes

branches:
  # Do not build PR branches in the main repo; only maintenance branches and
  # the merge results of PRs
  only:
  - master
  - 2.0.x

language: minimal

env:
  global:
  - PYENV=py37
  # Encrypted values for MESSAGE_IX_CI_USER, MESSAGE_IX_CI_PW,
  # MESSAGE_IX_GH_USER, MESSAGE_IX_GH_PW
  - secure: "IiNG8HMAFIrkeXnVMocSbAtXKgJ7SrZ9VduuAtdftImyBovbs2whtII5rL7qBg47mibREvY0ylUglmc5eLweEbZJO1zOVvNb8urk+cN4aljw9OubAlkpines9R0alhE1M2cOx94JYrNLPJyvMC8s40dVgCJzOM2kyP+cuf8Sr0vCgCAmbtsHSp7f3pkbvR+U7nSrPSHa/LHGtbQ2XJnhd8vvGeAn0oiP2c/Y6yCRhwI+EZYvh0uFSTf4XH6v/vs1zS+2qmWDMe5CUxXgXPtkPQqBhTmQDlbZXcnyoBIWtrpNAP8lXYv6piddizCg+HGpGkmef2pAnFwekQ6tCuQGyyamLlj6nFkljXHn1lbMoFPbRuH4N1vgh8h95r3HUo/Nfxdsza/PEs5HCOA03dU7rE6+ZrV5o0NRGf6cw0lR2evAmPBvkR66soWf3798T5JuUZib3fJ7XlBnhYisKw4Kr+IA6CJTlLVGZ1yd8YcW0bgUt881/kzC5lLjZEN3Is6PL5pkQO9H8tBLKuT0E+X5k6rJlxmuCtQawrpz+0LkoRjXWczH3SY4X7QU1N1Z7SGybNgsJCtwxYinq6QV1vHy2yhJjZtfn3iXtdU7mVyfGtOa3ZVkTO0MDWeDS2FiELz1hMV3zUC5rTZTkV4wLA88Cdijx9fiaW6tirVKhvMSwnI="

os:
- linux
- osx
# Turn this on once Travis Windows support improves
# - windows

cache:
  # Travis ensures these directories are created if they do not already exist
  directories:
  # - $HOME/miniconda/pkgs  # see https://github.com/iiasa/message_ix/pull/295
  - $HOME/.conda/pkgs
  - $HOME/.cache/message_ix

addons:
  apt:
    packages:
    - graphviz
  homebrew:
    packages:
    - graphviz

before_install:
  # Set other environment variables
  - . ci/env.sh
  # Download GAMS and Miniconda
  - . ci/travis-before_install.sh

install:
  # Install GAMS, conda, and Python dependencies needed for testing
  - . ci/travis-install.sh
  # Install the Python package
  - pip install --editable .[docs,reporting,tests,tutorial]

script:
  - python -c "import os, sys; assert os.environ['PYVERSION'] == sys.version[0]"
  # Run tests
  - pytest --verbose message_ix --cov-report=xml
  # Test that documentation can be built
  - cd doc && make html

after_success:
  - codecov
